/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ticketsystem.avro.route;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Schedule extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5586847525097728291L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Schedule\",\"namespace\":\"com.ticketsystem.avro.route\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"routeId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"departureTime\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}},{\"name\":\"arrivalTime\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}},{\"name\":\"totalSeats\",\"type\":\"int\"},{\"name\":\"availableSeats\",\"type\":\"int\"},{\"name\":\"basePrice\",\"type\":{\"type\":\"bytes\",\"logicalType\":\"decimal\",\"precision\":18,\"scale\":2}},{\"name\":\"isActive\",\"type\":\"boolean\"},{\"name\":\"createdAt\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}},{\"name\":\"updatedAt\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.Conversions.UUIDConversion());
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
    MODEL$.addLogicalTypeConversion(new org.apache.avro.Conversions.DecimalConversion());
  }

  private static final BinaryMessageEncoder<Schedule> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Schedule> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Schedule> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Schedule> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Schedule> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Schedule to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Schedule from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Schedule instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Schedule fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.util.UUID id;
  private java.util.UUID routeId;
  private java.time.Instant departureTime;
  private java.time.Instant arrivalTime;
  private int totalSeats;
  private int availableSeats;
  private java.math.BigDecimal basePrice;
  private boolean isActive;
  private java.time.Instant createdAt;
  private java.time.Instant updatedAt;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Schedule() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param routeId The new value for routeId
   * @param departureTime The new value for departureTime
   * @param arrivalTime The new value for arrivalTime
   * @param totalSeats The new value for totalSeats
   * @param availableSeats The new value for availableSeats
   * @param basePrice The new value for basePrice
   * @param isActive The new value for isActive
   * @param createdAt The new value for createdAt
   * @param updatedAt The new value for updatedAt
   */
  public Schedule(java.util.UUID id, java.util.UUID routeId, java.time.Instant departureTime, java.time.Instant arrivalTime, java.lang.Integer totalSeats, java.lang.Integer availableSeats, java.math.BigDecimal basePrice, java.lang.Boolean isActive, java.time.Instant createdAt, java.time.Instant updatedAt) {
    this.id = id;
    this.routeId = routeId;
    this.departureTime = departureTime.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
    this.arrivalTime = arrivalTime.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
    this.totalSeats = totalSeats;
    this.availableSeats = availableSeats;
    this.basePrice = basePrice;
    this.isActive = isActive;
    this.createdAt = createdAt.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
    this.updatedAt = updatedAt.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return routeId;
    case 2: return departureTime;
    case 3: return arrivalTime;
    case 4: return totalSeats;
    case 5: return availableSeats;
    case 6: return basePrice;
    case 7: return isActive;
    case 8: return createdAt;
    case 9: return updatedAt;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      new org.apache.avro.Conversions.UUIDConversion(),
      new org.apache.avro.Conversions.UUIDConversion(),
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      null,
      null,
      new org.apache.avro.Conversions.DecimalConversion(),
      null,
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.util.UUID)value$; break;
    case 1: routeId = (java.util.UUID)value$; break;
    case 2: departureTime = (java.time.Instant)value$; break;
    case 3: arrivalTime = (java.time.Instant)value$; break;
    case 4: totalSeats = (java.lang.Integer)value$; break;
    case 5: availableSeats = (java.lang.Integer)value$; break;
    case 6: basePrice = (java.math.BigDecimal)value$; break;
    case 7: isActive = (java.lang.Boolean)value$; break;
    case 8: createdAt = (java.time.Instant)value$; break;
    case 9: updatedAt = (java.time.Instant)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.util.UUID getId() {
    return id;
  }



  /**
   * Gets the value of the 'routeId' field.
   * @return The value of the 'routeId' field.
   */
  public java.util.UUID getRouteId() {
    return routeId;
  }



  /**
   * Gets the value of the 'departureTime' field.
   * @return The value of the 'departureTime' field.
   */
  public java.time.Instant getDepartureTime() {
    return departureTime;
  }



  /**
   * Gets the value of the 'arrivalTime' field.
   * @return The value of the 'arrivalTime' field.
   */
  public java.time.Instant getArrivalTime() {
    return arrivalTime;
  }



  /**
   * Gets the value of the 'totalSeats' field.
   * @return The value of the 'totalSeats' field.
   */
  public int getTotalSeats() {
    return totalSeats;
  }



  /**
   * Gets the value of the 'availableSeats' field.
   * @return The value of the 'availableSeats' field.
   */
  public int getAvailableSeats() {
    return availableSeats;
  }



  /**
   * Gets the value of the 'basePrice' field.
   * @return The value of the 'basePrice' field.
   */
  public java.math.BigDecimal getBasePrice() {
    return basePrice;
  }



  /**
   * Gets the value of the 'isActive' field.
   * @return The value of the 'isActive' field.
   */
  public boolean getIsActive() {
    return isActive;
  }



  /**
   * Gets the value of the 'createdAt' field.
   * @return The value of the 'createdAt' field.
   */
  public java.time.Instant getCreatedAt() {
    return createdAt;
  }



  /**
   * Gets the value of the 'updatedAt' field.
   * @return The value of the 'updatedAt' field.
   */
  public java.time.Instant getUpdatedAt() {
    return updatedAt;
  }



  /**
   * Creates a new Schedule RecordBuilder.
   * @return A new Schedule RecordBuilder
   */
  public static com.ticketsystem.avro.route.Schedule.Builder newBuilder() {
    return new com.ticketsystem.avro.route.Schedule.Builder();
  }

  /**
   * Creates a new Schedule RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Schedule RecordBuilder
   */
  public static com.ticketsystem.avro.route.Schedule.Builder newBuilder(com.ticketsystem.avro.route.Schedule.Builder other) {
    if (other == null) {
      return new com.ticketsystem.avro.route.Schedule.Builder();
    } else {
      return new com.ticketsystem.avro.route.Schedule.Builder(other);
    }
  }

  /**
   * Creates a new Schedule RecordBuilder by copying an existing Schedule instance.
   * @param other The existing instance to copy.
   * @return A new Schedule RecordBuilder
   */
  public static com.ticketsystem.avro.route.Schedule.Builder newBuilder(com.ticketsystem.avro.route.Schedule other) {
    if (other == null) {
      return new com.ticketsystem.avro.route.Schedule.Builder();
    } else {
      return new com.ticketsystem.avro.route.Schedule.Builder(other);
    }
  }

  /**
   * RecordBuilder for Schedule instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Schedule>
    implements org.apache.avro.data.RecordBuilder<Schedule> {

    private java.util.UUID id;
    private java.util.UUID routeId;
    private java.time.Instant departureTime;
    private java.time.Instant arrivalTime;
    private int totalSeats;
    private int availableSeats;
    private java.math.BigDecimal basePrice;
    private boolean isActive;
    private java.time.Instant createdAt;
    private java.time.Instant updatedAt;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.ticketsystem.avro.route.Schedule.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.routeId)) {
        this.routeId = data().deepCopy(fields()[1].schema(), other.routeId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.departureTime)) {
        this.departureTime = data().deepCopy(fields()[2].schema(), other.departureTime);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.arrivalTime)) {
        this.arrivalTime = data().deepCopy(fields()[3].schema(), other.arrivalTime);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.totalSeats)) {
        this.totalSeats = data().deepCopy(fields()[4].schema(), other.totalSeats);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.availableSeats)) {
        this.availableSeats = data().deepCopy(fields()[5].schema(), other.availableSeats);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.basePrice)) {
        this.basePrice = data().deepCopy(fields()[6].schema(), other.basePrice);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.isActive)) {
        this.isActive = data().deepCopy(fields()[7].schema(), other.isActive);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.createdAt)) {
        this.createdAt = data().deepCopy(fields()[8].schema(), other.createdAt);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.updatedAt)) {
        this.updatedAt = data().deepCopy(fields()[9].schema(), other.updatedAt);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
    }

    /**
     * Creates a Builder by copying an existing Schedule instance
     * @param other The existing instance to copy.
     */
    private Builder(com.ticketsystem.avro.route.Schedule other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.routeId)) {
        this.routeId = data().deepCopy(fields()[1].schema(), other.routeId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.departureTime)) {
        this.departureTime = data().deepCopy(fields()[2].schema(), other.departureTime);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.arrivalTime)) {
        this.arrivalTime = data().deepCopy(fields()[3].schema(), other.arrivalTime);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.totalSeats)) {
        this.totalSeats = data().deepCopy(fields()[4].schema(), other.totalSeats);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.availableSeats)) {
        this.availableSeats = data().deepCopy(fields()[5].schema(), other.availableSeats);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.basePrice)) {
        this.basePrice = data().deepCopy(fields()[6].schema(), other.basePrice);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.isActive)) {
        this.isActive = data().deepCopy(fields()[7].schema(), other.isActive);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.createdAt)) {
        this.createdAt = data().deepCopy(fields()[8].schema(), other.createdAt);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.updatedAt)) {
        this.updatedAt = data().deepCopy(fields()[9].schema(), other.updatedAt);
        fieldSetFlags()[9] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.util.UUID getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.ticketsystem.avro.route.Schedule.Builder setId(java.util.UUID value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.ticketsystem.avro.route.Schedule.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'routeId' field.
      * @return The value.
      */
    public java.util.UUID getRouteId() {
      return routeId;
    }


    /**
      * Sets the value of the 'routeId' field.
      * @param value The value of 'routeId'.
      * @return This builder.
      */
    public com.ticketsystem.avro.route.Schedule.Builder setRouteId(java.util.UUID value) {
      validate(fields()[1], value);
      this.routeId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'routeId' field has been set.
      * @return True if the 'routeId' field has been set, false otherwise.
      */
    public boolean hasRouteId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'routeId' field.
      * @return This builder.
      */
    public com.ticketsystem.avro.route.Schedule.Builder clearRouteId() {
      routeId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'departureTime' field.
      * @return The value.
      */
    public java.time.Instant getDepartureTime() {
      return departureTime;
    }


    /**
      * Sets the value of the 'departureTime' field.
      * @param value The value of 'departureTime'.
      * @return This builder.
      */
    public com.ticketsystem.avro.route.Schedule.Builder setDepartureTime(java.time.Instant value) {
      validate(fields()[2], value);
      this.departureTime = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'departureTime' field has been set.
      * @return True if the 'departureTime' field has been set, false otherwise.
      */
    public boolean hasDepartureTime() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'departureTime' field.
      * @return This builder.
      */
    public com.ticketsystem.avro.route.Schedule.Builder clearDepartureTime() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'arrivalTime' field.
      * @return The value.
      */
    public java.time.Instant getArrivalTime() {
      return arrivalTime;
    }


    /**
      * Sets the value of the 'arrivalTime' field.
      * @param value The value of 'arrivalTime'.
      * @return This builder.
      */
    public com.ticketsystem.avro.route.Schedule.Builder setArrivalTime(java.time.Instant value) {
      validate(fields()[3], value);
      this.arrivalTime = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'arrivalTime' field has been set.
      * @return True if the 'arrivalTime' field has been set, false otherwise.
      */
    public boolean hasArrivalTime() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'arrivalTime' field.
      * @return This builder.
      */
    public com.ticketsystem.avro.route.Schedule.Builder clearArrivalTime() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'totalSeats' field.
      * @return The value.
      */
    public int getTotalSeats() {
      return totalSeats;
    }


    /**
      * Sets the value of the 'totalSeats' field.
      * @param value The value of 'totalSeats'.
      * @return This builder.
      */
    public com.ticketsystem.avro.route.Schedule.Builder setTotalSeats(int value) {
      validate(fields()[4], value);
      this.totalSeats = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'totalSeats' field has been set.
      * @return True if the 'totalSeats' field has been set, false otherwise.
      */
    public boolean hasTotalSeats() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'totalSeats' field.
      * @return This builder.
      */
    public com.ticketsystem.avro.route.Schedule.Builder clearTotalSeats() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'availableSeats' field.
      * @return The value.
      */
    public int getAvailableSeats() {
      return availableSeats;
    }


    /**
      * Sets the value of the 'availableSeats' field.
      * @param value The value of 'availableSeats'.
      * @return This builder.
      */
    public com.ticketsystem.avro.route.Schedule.Builder setAvailableSeats(int value) {
      validate(fields()[5], value);
      this.availableSeats = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'availableSeats' field has been set.
      * @return True if the 'availableSeats' field has been set, false otherwise.
      */
    public boolean hasAvailableSeats() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'availableSeats' field.
      * @return This builder.
      */
    public com.ticketsystem.avro.route.Schedule.Builder clearAvailableSeats() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'basePrice' field.
      * @return The value.
      */
    public java.math.BigDecimal getBasePrice() {
      return basePrice;
    }


    /**
      * Sets the value of the 'basePrice' field.
      * @param value The value of 'basePrice'.
      * @return This builder.
      */
    public com.ticketsystem.avro.route.Schedule.Builder setBasePrice(java.math.BigDecimal value) {
      validate(fields()[6], value);
      this.basePrice = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'basePrice' field has been set.
      * @return True if the 'basePrice' field has been set, false otherwise.
      */
    public boolean hasBasePrice() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'basePrice' field.
      * @return This builder.
      */
    public com.ticketsystem.avro.route.Schedule.Builder clearBasePrice() {
      basePrice = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'isActive' field.
      * @return The value.
      */
    public boolean getIsActive() {
      return isActive;
    }


    /**
      * Sets the value of the 'isActive' field.
      * @param value The value of 'isActive'.
      * @return This builder.
      */
    public com.ticketsystem.avro.route.Schedule.Builder setIsActive(boolean value) {
      validate(fields()[7], value);
      this.isActive = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'isActive' field has been set.
      * @return True if the 'isActive' field has been set, false otherwise.
      */
    public boolean hasIsActive() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'isActive' field.
      * @return This builder.
      */
    public com.ticketsystem.avro.route.Schedule.Builder clearIsActive() {
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'createdAt' field.
      * @return The value.
      */
    public java.time.Instant getCreatedAt() {
      return createdAt;
    }


    /**
      * Sets the value of the 'createdAt' field.
      * @param value The value of 'createdAt'.
      * @return This builder.
      */
    public com.ticketsystem.avro.route.Schedule.Builder setCreatedAt(java.time.Instant value) {
      validate(fields()[8], value);
      this.createdAt = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'createdAt' field has been set.
      * @return True if the 'createdAt' field has been set, false otherwise.
      */
    public boolean hasCreatedAt() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'createdAt' field.
      * @return This builder.
      */
    public com.ticketsystem.avro.route.Schedule.Builder clearCreatedAt() {
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'updatedAt' field.
      * @return The value.
      */
    public java.time.Instant getUpdatedAt() {
      return updatedAt;
    }


    /**
      * Sets the value of the 'updatedAt' field.
      * @param value The value of 'updatedAt'.
      * @return This builder.
      */
    public com.ticketsystem.avro.route.Schedule.Builder setUpdatedAt(java.time.Instant value) {
      validate(fields()[9], value);
      this.updatedAt = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'updatedAt' field has been set.
      * @return True if the 'updatedAt' field has been set, false otherwise.
      */
    public boolean hasUpdatedAt() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'updatedAt' field.
      * @return This builder.
      */
    public com.ticketsystem.avro.route.Schedule.Builder clearUpdatedAt() {
      fieldSetFlags()[9] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Schedule build() {
      try {
        Schedule record = new Schedule();
        record.id = fieldSetFlags()[0] ? this.id : (java.util.UUID) defaultValue(fields()[0]);
        record.routeId = fieldSetFlags()[1] ? this.routeId : (java.util.UUID) defaultValue(fields()[1]);
        record.departureTime = fieldSetFlags()[2] ? this.departureTime : (java.time.Instant) defaultValue(fields()[2]);
        record.arrivalTime = fieldSetFlags()[3] ? this.arrivalTime : (java.time.Instant) defaultValue(fields()[3]);
        record.totalSeats = fieldSetFlags()[4] ? this.totalSeats : (java.lang.Integer) defaultValue(fields()[4]);
        record.availableSeats = fieldSetFlags()[5] ? this.availableSeats : (java.lang.Integer) defaultValue(fields()[5]);
        record.basePrice = fieldSetFlags()[6] ? this.basePrice : (java.math.BigDecimal) defaultValue(fields()[6]);
        record.isActive = fieldSetFlags()[7] ? this.isActive : (java.lang.Boolean) defaultValue(fields()[7]);
        record.createdAt = fieldSetFlags()[8] ? this.createdAt : (java.time.Instant) defaultValue(fields()[8]);
        record.updatedAt = fieldSetFlags()[9] ? this.updatedAt : (java.time.Instant) defaultValue(fields()[9]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Schedule>
    WRITER$ = (org.apache.avro.io.DatumWriter<Schedule>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Schedule>
    READER$ = (org.apache.avro.io.DatumReader<Schedule>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










