/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ticketsystem.avro.enums;
@org.apache.avro.specific.AvroGenerated
public enum TicketStatus implements org.apache.avro.generic.GenericEnumSymbol<TicketStatus> {
  AVAILABLE, BOOKED, CANCELLED, EXPIRED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"TicketStatus\",\"namespace\":\"com.ticketsystem.avro.enums\",\"symbols\":[\"AVAILABLE\",\"BOOKED\",\"CANCELLED\",\"EXPIRED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
